---
deployment:
  tasks:
    - export DEPLOYPATH=/home/c1865308c/public_html/surfwave
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R src $DEPLOYPATH
    - /bin/cp -R temp $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH